syntax = "proto3";

package openk.users.v1;

option go_package = "github.com/neox5/openk/internal/api_gen/openk/users/v1;usersv1";

import "openk/common/v1/context_v1.proto";
import "openk/common/v1/crypto_v1.proto";
import "openk/common/v1/error_v1.proto";
import "openk/users/v1/user_v1.proto";

service UserService {
  // CreateUser registers a new user
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {}
}

message CreateUserRequest {
  openk.common.v1.RequestContext context = 1;
  string username = 2;
  int32 iterations = 3;
  bytes salt = 4;
  bytes auth_key = 5;            // Raw auth key, will be hashed by service
  bytes public_key = 6;
  openk.common.v1.Ciphertext encrypted_key_pair = 7;
}

message CreateUserResponse {
  openk.common.v1.Error error = 1;
  UserProfile profile = 2;       // Only public user information returned
}
