syntax = "proto3";

package openk.users.v1;

option go_package = "github.com/neox5/openk/internal/api_gen/openk/users/v1;usersv1";

import "openk/common/v1/crypto_v1.proto";
import "google/protobuf/timestamp.proto";

// Public-facing user information.
message UserIdentity {
  string id = 1;                            // Unique user identifier.
  string username = 2;                      // Unique username.
  bytes public_key = 3;                     // User's public key.
  google.protobuf.Timestamp created_at = 4; // Account creation timestamp.
}
