syntax = "proto3";

package openk.users.v1;

option go_package = "github.com/neox5/openk/internal/api_gen/openk/users/v1;usersv1";

import "openk/common/v1/context_v1.proto";
import "openk/common/v1/crypto_v1.proto";
import "openk/common/v1/error_v1.proto";
import "openk/users/v1/user_v1.proto";

service UserService {
  // Registers a new user.
  rpc RegisterUser(RegisterUserRequest) returns (RegisterUserResponse);
}

message RegisterUserRequest {
  openk.common.v1.RequestContext context = 1;       // Request metadata (e.g., trace IDs).
  string username = 2;                              // Unique username for the user.
  int32 iterations = 3;                             // Key derivation iterations.
  bytes salt = 4;                                   // Salt for key derivation.
  bytes auth_key = 5;                               // Raw auth key to be hashed.
  bytes public_key = 6;                             // Public key of the user.
  openk.common.v1.Ciphertext encrypted_keypair = 7; // Encrypted asymmetric keypair.
}

message RegisterUserResponse {
  openk.common.v1.Error error = 1; // Error info if registration fails.
  UserIdentity identity = 2;       // Public-facing user information.
}
